### ISSUE TITLE
Remove transactions wrapper

### ISSUE THREAD

**Issue by fider** [bytetechnology/moleculer-context-db#5]
Library should not wrap actions into transactions it may cause deadlock:
- Action `A1` is opening transaction `T1`.
- Transaction pool is full, next transaction is possible when one of opened transations will be closed.
- Action `A1` calling action `A2`.
- Action `A2` wants to open transaction `T2` - it cannot, it is waiting for `T1` to be closed so `A2` execution is waiting.
- `T1` will never be closed as `T1` will close when `A1` will return - and `A1` will not return before `A2` subcall return.
- Result - timeout of waiting for `T2` to open or `T1` to close or `A2` call.

**Comment by ujwal-setlur** [comment]
Any reason the service action A1 cannot use an internal API instead of calling the external service action endpoint A2?
